### ISSUE TITLE
Yleiskartta-4500 / HallintoAlue contains Vaasa and Hammarland twice

### ISSUE THREAD

**Issue by jhimberg** [rOpenGov/gisfin#15]
kartta <- get_mml(map.id="Yleiskartta-4500", data.id="HallintoAlue")

kartta@data contains communes "Hammarland" and "Vaasa" twice

**Comment by jlehtoma** [comment]
Thanks for reporting this! If I remember correctly, the issue came up already once with Hammarland, but I guess it wasn't fixed. The reason is that the geographic entities of Hammarland and Vaasa actually constitute of 2 separate polygons. Since the attribute data for the polygons are exactly the same, these could be merged.

**Comment by jlehtoma** [comment]
Mock implementation

```
library(maptools)

kartta <- get_mml(map.id="Yleiskartta-4500", data.id="HallintoAlue")
attr_data <- as.data.frame(kartta)

union_kartta <- unionSpatialPolygons(kartta, kartta$Kunta)
# Get only 1st attribute data row ("Enklaavi") for each municipalityattr_data <- attr_data[which(attr_data$Enklaavi == 1),]
attr_data <- attr_data[which(attr_data$Enklaavi == 1),]attr_data <- attr_data[which(attr_data$Enklaavi == 1),]

# Use Kunta (ID) as row names
row.names(attr_data) <- attr_data$Kunta

kartta_merged <- SpatialPolygonsDataFrame(unioin_kartta, data=attr_data)

# TODO: set proj4string correctly (EPSG:3067?)
```

**Comment by jlehtoma** [comment]
Merge code now implemented in [avoindata/mml]() in [this commit](https://github.com/avoindata/mml/commit/1a246474059c04b13a3c6814c3f21d46ab752c48). Hammarland and Vaasa should only have 1 (multipart) polygon and 1 attribute table record.
